version: '3.9'

services:
  db:
    image: postgres:16
    container_name: nl2sql_pg
    environment:
      POSTGRES_USER: app
      POSTGRES_PASSWORD: app
      POSTGRES_DB: demo
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./db/init:/docker-entrypoint-initdb.d
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U app -d demo"]
      interval: 5s
      timeout: 3s
      retries: 10

  api:
    build: ./api
    container_name: nl2sql_api
    ports:
      - "8000:8000"
    depends_on:
      db:
        condition: service_healthy
    environment:
      DATABASE_URL: postgres://app:app@db:5432/demo

volumes:
  pgdata:
